### ISSUE TITLE
Toggle Columns does not work

### ISSUE THREAD

**Issue by Ofer-Gal** [unosquare/tubular-fabric#84]
The popup works but apply with any column off does not hide the column.

**Comment by kadosh** [comment]
Hi @Ofer-Gal,

We have fixed this, can you check with the latest version?

Thanks

**Comment by Ofer-Gal** [comment]
Works now. thx.
Is there a way to build the columns array in a function that based on the props, will push 5 columns or only 4 of them or other 4 of them?
When I did this with DetailedList, typescript gave me an error.
Thank you much

**Comment by kadosh** [comment]
I'm sure that's totally possible. In fact, tubular-fabric is doing that. We're creating columns conditionally. For example, the toggle functionality will create/remove fabric columns depending on the visible flag, because fabric doesn't support hiding columns.

I will close this issue as it is already been fixed.
